AWSTemplateFormatVersion: '2010-09-09'

Description:
  'RDS IaC'

Parameters:
  ProjectName:
    Type: String
  ENV:
    Type: String
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref ENV, 'prod']

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${ProjectName}-${ENV}-db-sg'
      VpcId: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-VPC'}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/db/${ENV}'
      GenerateSecretString:
        RequireEachIncludedType: True
        SecretStringTemplate: !Sub '{"username": "${ProjectName}"}'
        GenerateStringKey: 'password'
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
  RDSSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    DependsOn: RDSCluster
    Properties:
      SecretId: !Ref RDSSecret
      TargetId: !Ref RDSCluster
      TargetType: AWS::RDS::DBCluster
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${ENV}-db-subnet-group'
      DBSubnetGroupDescription: !Sub '${ProjectName}-${ENV}-db-subnet-group'
      SubnetIds:
        - {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet1'}
        - {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet2'}
  RDSCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    DependsOn: RDSSecret
    Properties:
      DBSubnetGroupName: !Ref RDSSubnetGroup
      DBClusterIdentifier: !Sub '${ProjectName}-${ENV}-db-cluster'
      Engine: aurora-postgresql
      EngineVersion: 14.6
      DBClusterParameterGroupName: default.aurora-postgresql14
      Port: 5432
      DatabaseName: !Ref ProjectName
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:password}}' ]]
      VpcSecurityGroupIds: [!GetAtt SecurityGroup.GroupId]
      EnableCloudwatchLogsExports:
        - postgresql
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${ENV}-db-instance'
      DBSubnetGroupName: !Ref RDSSubnetGroup
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref RDSCluster
      PubliclyAccessible: true
      DBInstanceClass: db.t4g.medium
  RDSAutoscalingRole:
    Type: AWS::IAM::Role
    Condition: IsProd
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ application-autoscaling.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: rds-autoscaling
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'application-autoscaling:*'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:DeleteAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'rds:DescribeServices'
                  - 'rds:UpdateService'
                  - 'rds:AddTagsToResource'
                  - 'rds:CreateDBInstance'
                  - 'rds:DeleteDBInstance'
                  - 'rds:DescribeDBClusters'
                  - 'rds:DescribeDBInstances'
                  - 'rds:ModifyDBCluster'
                Resource: '*'
  RDSScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: IsProd
    Properties:
      MinCapacity: 1
      MaxCapacity: 15
      ResourceId: !Join [':', [cluster, !Ref RDSCluster]]
      RoleARN: !GetAtt RDSAutoscalingRole.Arn
      ScalableDimension: rds:cluster:ReadReplicaCount
      ServiceNamespace: rds
  RDSScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: IsProd
    Properties:
      PolicyName: !Sub '${ProjectName}-${ENV}-db-asg-policy'
      ScalingTargetId: !Ref RDSScalingTarget
      PolicyType: TargetTrackingScaling
      ScalableDimension: rds:cluster:ReadReplicaCount
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: RDSReaderAverageCPUUtilization
        TargetValue: 80
        ScaleInCooldown: 60
        ScaleOutCooldown: 120

Outputs:
  WriterHost:
    Value: !GetAtt RDSCluster.Endpoint.Address
  ReaderHost:
    Value: !GetAtt RDSCluster.ReadEndpoint.Address

